### ISSUE TITLE
Is this still an active project?

### ISSUE THREAD

**Issue by gragra33** [magiccodingman/Magic.IndexedDb#4]
I am interested in what you are doing however I am wondering if this is still an active project before I commit to using it.

**Comment by magiccodingman** [comment]
I do plan to come back to this project, but I started it out of necessity for another project of mine. That other project is a major focus in my life. Also that other project is not open source. But due to changes in scope and plans, I'm not working on this as heavily at the moment. I'm hoping to get back to it in a few months, but I don't want to promise anything to be honest.
